kind: pipeline
type: docker
name: minimal-arm-build

steps:
  - name: build
    image: alpine:latest
    commands:
      - apk add --no-cache cmake make git gcc-arm-none-eabi
      - mkdir build && cd build
      - cmake -G "Ninja"
      - ninja
      
trigger:
  event:
    - pull_request
